#!/bin/bash

echo "THIS PACKAGE WILL ASSIST IN ERASING YOUR DEVICE, YOU AGREE TO USE THIS AT YOUR OWN RISK. THANKS FOR THE METHOD /u/changemylife99."
echo "If you would like to quit, exit Cydia NOW! This script will now purposefully hang for five seconds, then precede to some background activity before you will see anymore read-out"
sleep 5

echo "Updating your repos. This is needed to install MTerminal"

apt-get update 2> /dev/null

apt-get install com.officialscheduler.mterminal

echo "Done! Moving on to the actual erase!"

echo "Starting erase..."
rm /.installed_yaluX
echo "Removed Yalu file"

cd /var/mobile/

echo "Removing /var/mobile and it's contents..."

filecontent=(`ls | grep -v Library`)
for t in "${filecontent[@]}"
do
rm $t
done
echo "Removed all contents except for Library from /var/mobile."

echo "Removing the contents of /var/mobile/Library except for carrier settings and important files..."

cd /var/mobile/Library/

rm -R Accessibility
rm -R Accounts
rm -R AddressBook
rm -R AggregateDictionary
rm -R ApplePushService
rm -R Application Support
rm -R Assistant
rm -R BackBoard
rm -R BullitenBoard
rm -R Caches
rm -R Calender
rm -R CallDirectory
rm -R CallHistoryDB
rm -R CallHistoryTransactions
rm -R CallServices
rm -R ColorFlow 3
rm -R com.apple.internal.ck
rm -R com.apple.iTunesStore
rm -R com.apple.itunesstored
rm -R com.apple.nsurlsessionid
rm -R Cookies
rm -R CoreDuet
rm -R CoreFollowUp
rm -R CrashReporter
rm -R Cydia
rm -R DataAccess
rm -R DeviceRegistry.state
rm -R DifferentialPrivacy
rm -R DuetActivityScheudler
rm -R DuetExpertCenter
rm -R ExternalAccessory
rm -R FairPlay
rm -R FileProvider
rm -R FlurryFiles
rm -R FrontBoard
rm -R GameKit
rm -R GeoServices
rm -R Health
rm -R homed
rm -R iCleaner
rm -R IdentityServices
rm -R Inboxes
rm -R Keyboard
rm -R KeyboardServices
rm -R LASD
rm -R locationd
rm -R LockHTML
rm -R Logs
rm -R mad
rm -R Mail
rm -R MediaStream
rm -R Mobile Documents
rm -R MusicLibrary
rm -R NanoTimeKit
rm -R News
rm -R Notes
rm -R OnDemandResources
rm -R OTALogging
rm -R Passes
rm -R PickPocket
rm -R Reflectrix
rm -R ReplayKit
rm -R ResponseKit
rm -R Safari
rm -R Saved Application State
rm -R SMS
rm -R SoftwareUpdate
rm -R Spotlight
rm -R SpringBoard
rm -R Stats
rm -R Suggestions
rm -R SyncedPreferences
rm -R TCC
rm -R UserConfigurationProfiles
rm -R Voicemail
rm -R VoiceServices
rm -R VoiceTrigger
rm -R WatchConnectivity
rm -R WebClips
rm -R WebKit
rm -R WelcomeMat

echo "Removing stashed tweaks..."
cd /var/
rm stash

cd /var/db/
rm -R stash
tput bold
echo "Done!"
echo "PLEASE GO TO SETTINGS IMMEDIATLEY AND USE ERASE ALL CONTENTS AND SETTINGS!"
echo "PLEASE GO TO SETTINGS IMMEDIATLEY AND USE ERASE ALL CONTENTS AND SETTINGS!"
echo "PLEASE GO TO SETTINGS IMMEDIATLEY AND USE ERASE ALL CONTENTS AND SETTINGS!"
tput sgr0